import { useEffect, useState } from 'react'

// A custom hook = a normal function that uses React hooks inside. Anything
// starting with `use` can call other hooks. That's the whole rule.
//
// This one returns the current time and re-renders the component every second.
export function useNow(intervalMs = 1000) {
  const [now, setNow] = useState(() => Date.now())

  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), intervalMs)
    // The returned function runs when the component unmounts (or intervalMs
    // changes). Forget it and you leak a timer every time you switch tabs.
    return () => clearInterval(id)
  }, [intervalMs])

  return now
}

// A short beep, generated by the browser. No .mp3 file to ship or load.
export function beep() {
  try {
    const ctx = new AudioContext()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.frequency.value = 880
    gain.gain.setValueAtTime(0.2, ctx.currentTime)
    // Fade out instead of stopping abruptly — an abrupt stop clicks.
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.6)
    osc.start()
    osc.stop(ctx.currentTime + 0.6)
  } catch {
    // Browser blocked audio (usually: no user interaction yet). Not fatal.
  }
}
